### ISSUE TITLE
first crashed after then working

### ISSUE THREAD

**Issue by treakiandroid** [dotWee/OpenKWSolver#2]
hi and thanks a lot for this grate app,

i have installed the apk from https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk on my device. On the first try its crashed but after that it is working fine. here you got some information to fix that:

```
build.board: herring
build.bootloader: I9020XXLC2
build.brand: Google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: crespo
build.display: cm_crespo-userdebug 4.4.2 KVT49L 4182a2d618 test-keys
build.fingerprint: google/soju/crespo:4.1.2/JZO54K/485486:user/release-keys
build.hardware: herring
build.host: cyanogenmod
build.id: KVT49L
build.manufacturer: Samsung
build.model: Nexus S
build.product: soju
build.radio: unknown
build.serial: 3334DB72EFC600EC
build.tags: test-keys
build.time: 1396716656000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 4182a2d618
version.release: 4.4.2
version.sdk_int: 19


03-15 01:33:14.268 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk cmp=android/com.android.internal.app.ResolverActivity (has extras)} from pid 6888
03-15 01:33:16.932 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk flg=0x3000000 cmp=com.estrongs.android.pop/.app.BrowserDownloaderActivity (has extras)} from pid 6920
03-15 01:33:43.663 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk cmp=android/com.android.internal.app.ResolverActivity (has extras)} from pid 6888
03-15 01:33:47.374 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk flg=0x3000000 cmp=org.tint/.ui.activities.TintBrowserActivity (has extras)} from pid 6920
03-15 01:33:55.749 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk?raw=true cmp=android/com.android.internal.app.ResolverActivity} from pid 6996
03-15 01:33:58.241 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://github.com/dotWee/OpenKWSolver/blob/master/app-release.apk?raw=true flg=0x3000000 cmp=com.estrongs.android.pop/.app.BrowserDownloaderActivity} from pid 6920
03-15 01:34:12.807 I/PackageManager(424): Running dexopt on: de.dotwee.openkwsolver
03-15 01:34:18.944 I/ActivityManager(424): Force stopping de.dotwee.openkwsolver appid=10310 user=-1: update pkg
03-15 01:34:20.780 I/ThemeManager(1181): Handling new theme package: de.dotwee.openkwsolver
03-15 01:34:20.920 D/BackupManagerService(424): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.dotwee.openkwsolver flg=0x4000010 (has extras) }
03-15 01:34:26.452 I/ActivityManager(6952): Timeline: Activity_launch_request id:de.dotwee.openkwsolver time:1373896
03-15 01:34:26.456 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=de.dotwee.openkwsolver cmp=de.dotwee.openkwsolver/.MainActivity} from pid 6952
03-15 01:34:26.776 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=7141 uid=10310 gids={50310, 3003}
03-15 01:34:28.901 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{420c9398 u0 de.dotwee.openkwsolver/.MainActivity t13} time:1376346
03-15 01:34:33.721 D/FDroid  (7209): PackageReceiver received [action = 'android.intent.action.PACKAGE_ADDED', data = 'package:de.dotwee.openkwsolver']
03-15 01:34:33.831 D/FDroid  (7209): Inserting installed app info for 'de.dotwee.openkwsolver' (v13)
03-15 01:35:55.764 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{420c9398 u0 de.dotwee.openkwsolver/.MainActivity t13} time:1463208
03-15 01:36:25.354 I/MainActivity(7141): ID Request URL: http://www.9kw.eu:80/index.cgi?action=usercaptchanew&apikey=XXXXXXXXX&source=androidopenkws&confirm=0&mouse=0&nocaptcha=1
03-15 01:36:25.354 I/DownloadContentTask(7141): input: http://www.9kw.eu:80/index.cgi?action=usercaptchanew&apikey=XXXXXXXXX&source=androidopenkws&confirm=0&mouse=0&nocaptcha=1
03-15 01:36:30.178 W/System.err(7141):  at de.dotwee.openkwsolver.Tools.DownloadContentTask.doInBackground(DownloadContentTask.java:48)
03-15 01:36:30.178 W/System.err(7141):  at de.dotwee.openkwsolver.Tools.DownloadContentTask.doInBackground(DownloadContentTask.java:31)
03-15 01:36:30.186 I/pullCaptchaPicture(7141): URL: http://www.9kw.eu:80/index.cgi?action=usercaptchashow&source=androidopenkws&confirm=0&mouse=0&id=&apikey=XXXXXXXXX
03-15 01:36:30.210 D/DownloadImageTask(7141): input URL: http://www.9kw.eu:80/index.cgi?action=usercaptchashow&source=androidopenkws&confirm=0&mouse=0&id=&apikey=XXXXXXXXX
03-15 01:36:30.272 W/System.err(7141):  at de.dotwee.openkwsolver.Tools.DownloadImageTask.doInBackground(DownloadImageTask.java:41)
03-15 01:36:30.276 W/System.err(7141):  at de.dotwee.openkwsolver.Tools.DownloadImageTask.doInBackground(DownloadImageTask.java:27)
03-15 01:36:30.401 I/InputDispatcher(424): Window 'Window{42123848 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2309.1ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=0, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (86.7, 445.0)]), policyFlags=0x47000000
03-15 01:36:30.401 I/InputDispatcher(424): Window 'Window{42123848 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2152.5ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=1, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (86.7, 445.0)]), policyFlags=0x47000000
03-15 01:36:51.905 E/AndroidRuntime(7141): Process: de.dotwee.openkwsolver, PID: 7141
03-15 01:36:51.905 E/AndroidRuntime(7141): java.lang.RuntimeException: Unable to destroy activity {de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}: java.lang.NullPointerException
03-15 01:36:51.905 E/AndroidRuntime(7141):  at de.dotwee.openkwsolver.Fragments.SolverFragment.onDestroy(SolverFragment.java:187)
03-15 01:36:55.167 I/WindowState(424): WIN DEATH: Window{42123848 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}
03-15 01:36:55.170 I/ActivityManager(424): Process de.dotwee.openkwsolver (pid 7141) has died.
03-15 01:37:34.577 I/ActivityManager(1246): Timeline: Activity_launch_request id:de.dotwee.openkwsolver time:1562019
03-15 01:37:34.577 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.dotwee.openkwsolver/.MainActivity} from pid 1246
03-15 01:37:34.717 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=9220 uid=10310 gids={50310, 3003}
03-15 01:37:36.163 I/ActivityManager(424): Displayed de.dotwee.openkwsolver/.MainActivity: +1s467ms
03-15 01:37:36.167 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{420c9398 u0 de.dotwee.openkwsolver/.MainActivity t17} time:1563609
```

thanks, greetings and keep up the good work

**Comment by treakiandroid** [comment]
now it isnt working anymore...

```
03-15 10:41:35.179 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.dotwee.openkwsolver/.MainActivity} from pid 1246
03-15 10:41:35.336 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=13674 uid=10310 gids={50310, 3003}
03-15 10:42:09.554 I/WindowManager(424): Input event dispatching timed out sending to de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
03-15 10:42:12.773 E/ActivityManager(424): ANR in de.dotwee.openkwsolver (de.dotwee.openkwsolver/.MainActivity)
03-15 10:42:12.773 E/ActivityManager(424):   9% 13674/de.dotwee.openkwsolver: 7.2% user + 1.8% kernel / faults: 375 minor 11 major
03-15 10:42:12.773 E/ActivityManager(424):   6% 13674/de.dotwee.openkwsolver: 6% user + 0% kernel / faults: 17 minor
03-15 10:42:15.379 I/WindowState(424): WIN DEATH: Window{422634b0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}
03-15 10:42:15.816 I/ActivityManager(424): Process de.dotwee.openkwsolver (pid 13674) has died.
03-15 10:42:15.820 W/ActivityManager(424): Force removing ActivityRecord{420b8578 u0 de.dotwee.openkwsolver/.MainActivity t21}: app died, no saved state
03-15 10:42:22.097 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.dotwee.openkwsolver/.MainActivity} from pid 1246
03-15 10:42:22.230 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=13756 uid=10310 gids={50310, 3003}
03-15 10:43:19.449 I/WindowManager(424): Input event dispatching timed out sending to de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
03-15 10:43:21.722 E/ActivityManager(424): ANR in de.dotwee.openkwsolver (de.dotwee.openkwsolver/.MainActivity)
03-15 10:43:21.722 E/ActivityManager(424):   15% 13756/de.dotwee.openkwsolver: 12% user + 2.6% kernel / faults: 939 minor
03-15 10:43:21.722 E/ActivityManager(424):   2.9% 13756/de.dotwee.openkwsolver: 2.9% user + 0% kernel / faults: 1 minor
03-15 10:43:23.945 I/ActivityManager(424): Process de.dotwee.openkwsolver (pid 13756) has died.
03-15 10:43:23.949 I/WindowState(424): WIN DEATH: Window{4255cd80 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}
03-15 10:43:24.089 W/ActivityManager(424): Force removing ActivityRecord{41f0b3d0 u0 de.dotwee.openkwsolver/.MainActivity t22}: app died, no saved state
03-15 10:43:33.515 I/ActivityManager(1246): Timeline: Activity_launch_request id:de.dotwee.openkwsolver time:5609268
03-15 10:43:33.519 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.dotwee.openkwsolver/.MainActivity} from pid 1246
03-15 10:43:33.984 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=13989 uid=10310 gids={50310, 3003}
03-15 10:43:35.625 I/ActivityManager(424): Displayed de.dotwee.openkwsolver/.MainActivity: +1s663ms
03-15 10:43:35.629 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{424f7530 u0 de.dotwee.openkwsolver/.MainActivity t23} time:5611380
03-15 10:43:39.027 I/ActivityManager(424):   fore  T    19663 kB: de.dotwee.openkwsolver (13989) top-activity
03-15 10:43:40.105 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:43:45.078 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:43:50.089 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:43:55.070 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:00.086 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:05.070 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:10.074 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:15.074 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:19.375 I/ActivityManager(424): START u0 {act=android.intent.action.VIEW dat=https://github.com/dotWee/OpenKWSolver cmp=org.tint/.ui.activities.TintBrowserActivity} from pid 13989
03-15 10:44:20.070 I/DownloadContentTask(13989): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:44:23.543 I/ActivityManager(424): Process de.dotwee.openkwsolver (pid 13989) has died.
03-15 10:44:23.543 I/WindowState(424): WIN DEATH: Window{42557fd0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}
03-15 10:46:15.390 I/ActivityManager(1246): Timeline: Activity_launch_request id:de.dotwee.openkwsolver time:5771141
03-15 10:46:15.390 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.dotwee.openkwsolver/.MainActivity} from pid 1246
03-15 10:46:15.535 I/ActivityManager(424): Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=14446 uid=10310 gids={50310, 3003}
03-15 10:46:16.597 I/ActivityManager(424): Displayed de.dotwee.openkwsolver/.MainActivity: +1s81ms
03-15 10:46:16.597 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{42360ed8 u0 de.dotwee.openkwsolver/.MainActivity t24} time:5772349
03-15 10:46:21.269 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:26.242 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:31.242 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:36.226 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:41.222 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:45.953 I/MainActivity(14446): ID Request URL: http://www.9kw.eu:80/index.cgi?action=usercaptchanew&apikey=XXXXXXXXX&source=androidopenkws&confirm=0&mouse=0&nocaptcha=1
03-15 10:46:45.957 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchanew&apikey=XXXXXXXXX&source=androidopenkws&confirm=0&mouse=0&nocaptcha=1
03-15 10:46:51.113 W/System.err(14446):     at de.dotwee.openkwsolver.Tools.DownloadContentTask.doInBackground(DownloadContentTask.java:48)
03-15 10:46:51.117 W/System.err(14446):     at de.dotwee.openkwsolver.Tools.DownloadContentTask.doInBackground(DownloadContentTask.java:31)
03-15 10:46:51.230 I/pullCaptchaPicture(14446): URL: http://www.9kw.eu:80/index.cgi?action=usercaptchashow&source=androidopenkws&confirm=0&mouse=0&id=&apikey=XXXXXXXXX
03-15 10:46:51.230 D/DownloadImageTask(14446): input URL: http://www.9kw.eu:80/index.cgi?action=usercaptchashow&source=androidopenkws&confirm=0&mouse=0&id=&apikey=XXXXXXXXX
03-15 10:46:53.394 I/InputDispatcher(424): Application is not responding: Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}.  It has been 5004.1ms since event, 5003.7ms since wait started.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
03-15 10:46:53.421 I/WindowManager(424): Input event dispatching timed out sending to de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
03-15 10:46:54.410 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6615.4ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=0, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (304.7, 610.7)]), policyFlags=0x47000000
03-15 10:46:54.414 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6605.8ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (299.5, 612.4)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6598.6ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (268.1, 614.1)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6585.9ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (245.2, 613.2)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6571.3ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (215.2, 609.9)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6556.9ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (173.9, 606.5)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6542.2ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (137.3, 606.5)]), policyFlags=0x47000000
03-15 10:46:54.421 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6527.7ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (107.3, 605.7)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6513.4ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (73.1, 607.4)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6498.8ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (50.6, 607.4)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6484.2ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (31.9, 608.2)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6469.8ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (20.6, 608.2)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6455.3ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (8.9, 608.2)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6440.8ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (4.2, 606.5)]), policyFlags=0x47000000
03-15 10:46:54.425 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 6387.1ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=1, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (4.2, 606.5)]), policyFlags=0x47000000
03-15 10:46:54.457 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:55.777 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2866.4ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (385.8, 650.3)]), policyFlags=0x47000000
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2866.6ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (350.6, 639.3)]), policyFlags=0x47000000
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2866.9ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (315.9, 630.1)]), policyFlags=0x47000000
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2867.0ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (274.7, 617.5)]), policyFlags=0x47000000
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2867.2ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (230.2, 607.4)]), policyFlags=0x47000000
03-15 10:46:57.293 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2867.4ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (186.6, 598.1)]), policyFlags=0x47000000
03-15 10:46:57.296 I/InputDispatcher(424): Window 'Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}' spent 2868.1ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.1, yPrecision=1.2, displayId=0, pointers=[0: (135.0, 589.7)]), policyFlags=0x47000000
03-15 10:46:57.504 I/DownloadContentTask(14446): input: http://www.9kw.eu:80/index.cgi?action=usercaptchaguthaben&source=androidopenkws&apikey=XXXXXXXXX
03-15 10:46:58.086 E/ActivityManager(424): ANR in de.dotwee.openkwsolver (de.dotwee.openkwsolver/.MainActivity)
03-15 10:46:58.086 E/ActivityManager(424):   2.2% 14446/de.dotwee.openkwsolver: 1.7% user + 0.4% kernel / faults: 699 minor 34 major
03-15 10:46:58.086 E/ActivityManager(424):   14% 14446/de.dotwee.openkwsolver: 12% user + 1.8% kernel / faults: 79 minor 9 major
03-15 10:46:58.086 E/ActivityManager(424):     12% 14446/ee.openkwsolver: 11% user + 1.8% kernel
03-15 10:46:58.461 F/libc    (14446): Fatal signal 6 (SIGABRT) at 0x000001a8 (code=0), thread 14446 (ee.openkwsolver)
03-15 10:46:58.574 I/DEBUG   (93): pid: 14446, tid: 14446, name: ee.openkwsolver  >>> de.dotwee.openkwsolver <<<
03-15 10:47:00.992 I/WindowState(424): WIN DEATH: Window{420c0ea0 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}
03-15 10:47:00.996 W/InputDispatcher(424): channel '420c0ea0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
03-15 10:47:00.996 E/InputDispatcher(424): channel '420c0ea0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-15 10:47:01.007 W/InputDispatcher(424): Attempted to unregister already unregistered input channel '420c0ea0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)'
03-15 10:47:02.230 I/ActivityManager(424): Process de.dotwee.openkwsolver (pid 14446) has died.
03-15 10:47:02.234 W/ActivityManager(424): Force removing ActivityRecord{42360ed8 u0 de.dotwee.openkwsolver/.MainActivity t24}: app died, no saved state
```

**Comment by dotWee** [comment]
Thanks for your report! Problem were at the onDestroy method as logcat says: <code>de.dotwee.openkwsolver.Fragments.SolverFragment.onDestroy(SolverFragment.java:187)</code> 
I think i fixed it. Would you mind testing the [fix debug version](http://dotwee.de/openkwsolver/app-debug.apk) and report again if the error still exist?
